language: c
install: |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]
      then
      wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-3/CUnit-2.1-3.tar.bz2 &&
      tar -jxf CUnit-2.1-3.tar.bz2 &&
      pushd CUnit-2.1-3 &&
      autoreconf -i &&
      ./configure --prefix=/usr &&
      make &&
      sudo make install &&
      popd
    fi
    if [ "${TRAVIS_OS_NAME}" = "osx" ]
      then
      brew update
      brew install cunit
    fi
branches:
    only:
        - master
script: make && make test
compiler:
    - gcc
    - clang
os:
    - linux
    - osx
