language: c
install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -qq libcunit1 libcunit1-dev; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; brew install cunit; fi
branches:
    only:
        - master
script: make && make test
compiler:
    - gcc
    - clang
os:
    - linux
    - osx
